Use versioning, zusammen and session libs from sdc-common-be
zusammen-lib in sdc-common-be uses cassandra 3.6.0 withoutJMXReporting
(cassandra 3.4.0 with spring boot 2.1.0 caused:
java.lang.NoClassDefFoundError: com/codahale/metrics/JmxReporter)

Bump to version 1.5.2

Change-Id: I6786b0dfec6c4052ae775fcb478aba4b23cf805f
Issue-ID: SDC-2541
Signed-off-by: talig <talig@amdocs.com>