Fix throwing an UnsatisfiedDependencyException upon starting
The UnsatisfiedDependencyException is finally caused by
ClassNotFoundException: c.g.c.u.c.FutureFallback.
That was fixed by upgrading the spring boot version to 2.1.0.RELEASE.
By doing that the cassandra version was upgraded to version 3.6.0,
which doesn't require the FutureFallback class.

Issue-ID: SDC-2557
Signed-off-by: Piotr Borelowski <p.borelowski@partner.samsung.com>
Change-Id: I79d6d717dadebe1754e976553ac11966be6eca8b