Use versioning, zusammen and session libs from sdc-common-be
zusammen-lib in sdc-common-be uses cassandra 3.6.0 withoutJMXReporting
(cassandra 3.4.0 with spring boot 2.1.0 caused:
java.lang.NoClassDefFoundError: com/codahale/metrics/JmxReporter)

update spring version to 2.1.5

Change-Id: I17ce7b4489330831bc5d9c0a1803f2e21ba6f98a
Issue-ID: SDC-2541
Signed-off-by: talig <talig@amdocs.com>